services:
  master_postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    networks:
      - blog_network

  blog_app:
    build: .
    depends_on:
      - master_postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://master_postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - '8080:8080'
    networks:
      - blog_network

networks:
  blog_network:
    driver: bridge